'use client';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/partials/Sidebar';
import './globals.css';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { usePathname } from 'next/navigation';
import Head from 'next/head';

const inter = Inter({
  subsets: ['latin'],
});

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <Head>
        <title>Spotify Portal</title>
        <link
          rel="icon"
          href="/spotify_logo.png"
        />
        <description content="Generated by create next app" />
      </Head>
      <body className={`h-screen ${inter.className}`}>
        {pathname === '/login' ? (
          children
        ) : (
          <main className="flex w-full h-full">
            <Sidebar />
            <section className="flex-1 overflow-y-auto p-8">{children}</section>
          </main>
        )}
      </body>
    </html>
  );
}
