import Image from 'next/image';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/partials/Sidebar';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Spotify Portal',
  description: 'Generated by create next app',
  icons: {
    icon: '/spotify_logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-screen ${inter.className}`}>
        <main className="flex w-full h-full">
          <Sidebar />
          <section className="overflow-y-auto p-8">{children}</section>
        </main>
      </body>
    </html>
  );
}
